# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200
  tensorboard_logdir: tb

checkpoint:
  save_interval: 5
  save_interval_updates: 20000
  keep_interval_updates: 25
  no_epoch_checkpoints: true
  load_checkpoint_on_all_dp_ranks: true

task:
  _name: semi_dinosr_pretraining
  data: ???
  label_dir: ???
  labels: ???
  label_rate: ${model.label_rate}
  sample_rate: 16000
  max_sample_size: 320000
  min_sample_size: 32000
  pad_audio: false
  random_crop: true
  normalize: true # must be consistent with extractor

dataset:
  num_workers: 12
  max_tokens: 4350000 # 3800000
  skip_invalid_size_inputs_valid_test: true
  validate_interval: 5
  required_batch_size_multiple: 1
  disable_validation: true

distributed_training:
  distributed_world_size: 7 #16
  ddp_backend: legacy_ddp

criterion:
  _name: semi_model
  loss_weights: 
    m_loss: 1.0
    l_loss: 1.0
    u_loss: 1.0
  log_keys:
    - ema_decay
    - target_ppl
    - pred_ppl
    - codebook_decay
    - student_accuracy
    - teacher_accuracy
    - l_loss_scale
    - u_loss_scale

optimization:
  max_update: 400000
  lr: [0.0005]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.03,0.47,0.50]

model:
  _name: MTdinosr
  extractor_mode: layer_norm
  encoder_layerdrop: 0.05
  dropout_input: 0.0
  dropout_features: 0.0
  feature_grad_mult: 1.0
  encoder_embed_dim: 768

  discrete: true
  codebook_size: 256   # modified
  average_top_k_layers: 8
  normal_init_codebook: false
  codebook_init_decay: 0.9
  instance_norm_target_layer: true

  mask_prob: 0.8
  mask_length: 10

  pos_conv_depth: 5
  conv_pos: 95

  ema_decay: 0.999
  ema_end_decay: 0.9999
  ema_anneal_end_step: 30000
  ema_transformer_only: true
  ema_layers_only: true

  require_same_masks: true
  mask_dropout: 0
